@IntegraMinimalApi_HostAddress = https://localhost:7134


POST {{IntegraMinimalApi_HostAddress}}/appuser
Content-Type: application/json

{
  "name": "string",
  "lastName": "string",
  "dateOfBirth": "2024-05-22",
  "country": "string",
  "city": "string",
  "street": "string",
  "houseNumber": 2147483647
}
###

GET {{IntegraMinimalApi_HostAddress}}/appuser/2
Content-Type: application/json
###

GET {{IntegraMinimalApi_HostAddress}}/appuser
Content-Type: application/json
###
